import React from 'eact';
import { Autocomplete } from '@material-ui/core';

const CustomAutocomplete = ({
  options,
  aria-describedby,
  aria-label,
  aria-labelledby,
  autoComplete,
  autoFocus,
  autoHighlight,
  autoSelect,
  blurOnSelect,
  clearIcon,
  clearOnBlur,
  clearOnEscape,
  clearText,
  closeText,
  color,
  defaultValue,
  disableClearable,
  disableCloseOnSelect,
  disabled,
  disabledItemsFocusable,
  disableListWrap,
  endDecorator,
  error,
  filterOptions,
  filterSelectedOptions,
  forcePopupIcon,
  freeSolo,
  getLimitTagsText,
  getOptionDisabled,
  getOptionKey,
  getOptionLabel,
  groupBy,
  handleHomeEndKeys,
  id,
  includeInputInList,
  inputValue,
  isOptionEqualToValue,
  limitTags,
  loading,
  loadingText,
  multiple,
  name,
  noOptionsText,
  onChange,
  onClose,
  onHighlightChange,
  onInputChange,
  onOpen,
  open,
  openOnFocus,
  openText,
  placeholder,
  popupIcon,
  readOnly,
  renderGroup,
  renderOption,
  renderTags,
  required,
  selectOnFocus,
  size,
  slotProps,
  slots,
  startDecorator,
  sx,
  type,
  value,
  variant,
}) => {
  return (
    <Autocomplete
      options={options}
      aria-describedby={aria-describedby}
      aria-label={aria-label}
      aria-labelledby={aria-labelledby}
      autoComplete={autoComplete}
      autoFocus={autoFocus}
      autoHighlight={autoHighlight}
      autoSelect={autoSelect}
      blurOnSelect={blurOnSelect}
      clearIcon={clearIcon}
      clearOnBlur={clearOnBlur}
      clearOnEscape={clearOnEscape}
      clearText={clearText}
      closeText={closeText}
      color={color}
      defaultValue={defaultValue}
      disableClearable={disableClearable}
      disableCloseOnSelect={disableCloseOnSelect}
      disabled={disabled}
      disabledItemsFocusable={disabledItemsFocusable}
      disableListWrap={disableListWrap}
      endDecorator={endDecorator}
      error={error}
      filterOptions={filterOptions}
      filterSelectedOptions={filterSelectedOptions}
      forcePopupIcon={forcePopupIcon}
      freeSolo={freeSolo}
      getLimitTagsText={getLimitTagsText}
      getOptionDisabled={getOptionDisabled}
      getOptionKey={getOptionKey}
      getOptionLabel={getOptionLabel}
      groupBy={groupBy}
      handleHomeEndKeys={handleHomeEndKeys}
      id={id}
      includeInputInList={includeInputInList}
      inputValue={inputValue}
      isOptionEqualToValue={isOptionEqualToValue}
      limitTags={limitTags}
      loading={loading}
      loadingText={loadingText}
      multiple={multiple}
      name={name}
      noOptionsText={noOptionsText}
      onChange={onChange}
      onClose={onClose}
      onHighlightChange={onHighlightChange}
      onInputChange={onInputChange}
      onOpen={onOpen}
      open={open}
      openOnFocus={openOnFocus}
      openText={openText}
      placeholder={placeholder}
      popupIcon={popupIcon}
      readOnly={readOnly}
      renderGroup={renderGroup}
      renderOption={renderOption}
      renderTags={renderTags}
      required={required}
      selectOnFocus={selectOnFocus}
      size={size}
      slotProps={slotProps}
      slots={slots}
      startDecorator={startDecorator}
      sx={sx}
      type={type}
      value={value}
      variant={variant}
    />
  );
};

export default CustomAutocomplete;